### ISSUE TITLE
Plugin not listed in Certbot documentation

### ISSUE THREAD

**Issue by bernhardfrenking** [domeneshop/certbot-dns-domeneshop#11]
In the documentation of certbot ([certbot DNS Plugins](https://eff-certbot.readthedocs.io/en/latest/using.html#dns-plugins)], this plugin is not mentioned. 

Is there a reaseon for it?
Is this plugin still working with the latest version of certbot?

**Comment by eirikrye** [comment]
Yes, the plugin is working with the latest version of certbot. The page you've provided only lists major providers, but is by no means an exhaustive list.
