### ISSUE TITLE
minor adjustment in documentation...

### ISSUE THREAD

**Issue by reidaragasoster** [domeneshop/certbot-dns-domeneshop#4]
using certbot 1.9.0

Exampe:

from

certbot certonly \
  --authenticator certbot-dns-domeneshop:dns-domeneshop \
  --certbot-dns-domeneshop:dns-domeneshop-credentials ~/.secrets/certbot/domeneshop.ini \
  --certbot-dns-domeneshop:dns-domeneshop-propagation-seconds 120 \
  -d example.com \
  -d www.example.com

to

certbot certonly \
  --authenticator dns-domeneshop \
  --certbot-dns-domeneshop:dns-domeneshop-credentials ~/.secrets/certbot/domeneshop.ini \
  --certbot-dns-domeneshop:dns-domeneshop-propagation-seconds 120 \
  -d example.com \
  -d www.example.com

credentials.ini

from:

certbot_dns_domeneshop:dns_domeneshop_client_token=1234567890abcdef
certbot_dns_domeneshop:dns_domeneshop_client_secret=1234567890abcdefghijklmnopqrstuvxyz1234567890abcdefghijklmnopqrs

to
dns_domeneshop_client_token=1234567890abcdef
dns_domeneshop_client_secret=1234567890abcdefghijklmnopqrstuvxyz1234567890abcdefghijklmnopqrs

**Comment by eirikrye** [comment]
Please see #2.

Certbot recently made a change to allow using either only non-prefixed argument (`--authenticator dns-domeneshop` with `--dns-domeneshop-credentials`) or only prefixed arguments (`--authenticator certbot-dns-domeneshop:dns-domeneshop ` with `--certbot-dns-domeneshop:dns-domeneshop-credentials`).

In your revised example, you are mixing the two, which was tested as an invalid configuration while I was reviewing #2. Are you sure it even works? If so, what version of certbot? Ideally, you should remove the `certbot-dns-domeneshop:` from -every- parameter in that case.

**Comment by reidaragasoster** [comment]
.. as commented i use certbot 1.9.0

**Comment by eirikrye** [comment]
Your second example does not work in certbot 1.9.0. Using `--authenticator dns-domeneshop` tells Certbot to expect non-prefixed arguments, but you are using the prefix in the next argument.

```
~# certbot certonly --authenticator dns-domeneshop --certbot-dns-domeneshop:dns-domeneshop-credentials ~/.secrets/certbot/domeneshop.ini -d example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-domeneshop, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.com
Cleaning up challenges
File not found: /etc/letsencrypt/domeneshop.ini
```

Either you have to remove **all** of the `certbot-dns-domeneshop:` prefixes, or none of them. The example is correct and will remain with prefixes, because the prefixed arguments work the same in both Certbot 1.7.0+ as well as the older versions that are packaged for Debian/Ubuntu and so on.

**Comment by eirikrye** [comment]
I pushed an update to the README to show the alternative, non-prefixed usage: 842018f8f35ca92bb9acdf7c9993106a1bb84b80
