### ISSUE TITLE
Feature request: custom Kubernetes cert-manager webhook DNS01 challenge resolver 

### ISSUE THREAD

**Issue by thomastvedt** [domeneshop/certbot-dns-domeneshop#5]
Hello, `certbot-dns-domeneshop` is great when using certbot! 👍🏼 

We recently switched to Kubernetes which uses a similar concept as certbot called [cert-manager](https://cert-manager.io/docs/installation/kubernetes/). Cert-manager works great for requesting regular certificates from letsencrypt, but for wildcard certificates we need to hook up a DNS01 challenge resolver. Cert-manager supports a few well-known DNS providers, and has a webhook option which allows DNS providers to add support.   
[custom cert-manager webhook implementation](https://cert-manager.io/docs/configuration/acme/dns01/webhook/).   

It would be awesome if you could develop a custom cert-manager webhook implementation 🍰 🌻  What do you think? 😄

**Comment by eirikrye** [comment]
Hi,

Thanks for the request! We use cert-manager in our parts of our infrastructure as well, so this is definitely something we want to get around to implementing (with a corresponding Go wrapper around the DNS API).

I'll update this issue as soon as there is any progress, but unfortunately I cannot guarantee that it will be very soon.

If anyone in the community wants to look at this in the meantime (based on the [api documentation](https://api.domeneshop.no/docs/)), we would be willing to hop on as a contributor to that project.

**Comment by thomastvedt** [comment]
Hi, we did consider implementing this ourselves, but we couldn't find time for it right now unfortunately. It seems pretty straight forward, but I have a few questions:
- Are you planning to support limiting the API user's access? It would be nice if the API user didn't have access to everything.
- I noticed that the API key expires after one year, what is the reason for this?

We ended up using Azure DNS for the subdomain where we wanted to support DNS01 challenges.

**Comment by eirikrye** [comment]
Hi again,

We have now created a cert-manager webhook, which is available at https://github.com/domeneshop/cert-manager-webhook-domeneshop. Feel free to try it out for any of your domains.

As for your other questions:

> Are you planning to support limiting the API user's access? It would be nice if the API user didn't have access to everything.

Internally our system supports limiting the token access, but we have no GUI for it in the control panel. If you to add restrictions to your tokens (e.g. only for specific domains), you may contact customer support to have us set those restrictions.

> I noticed that the API key expires after one year, what is the reason for this?

It was done simply as a measure to prevent forgotten API tokens from being abused. We'll probably make the expiry time configurable in the control panel at some point.

**Comment by thomastvedt** [comment]
Hi, that was really quick and awesome! Thank you :)
