### ISSUE TITLE
module 'certbot.interfaces' has no attribute 'IAuthenticator'

### ISSUE THREAD

**Issue by atlekberg** [domeneshop/certbot-dns-domeneshop#7]
Just discovered this. From version 2.0.0 of Certbot they have removed zope.

More info:
- https://github.com/certbot/certbot/pull/8950
- https://github.com/certbot/certbot/issues/9427

Workaround is to run the previous version of Certbot.

**Comment by eirikrye** [comment]
Thanks for the report. This should now be fixed in 0.2.9:

```
pip3 install --upgrade certbot-dns-domeneshop
```
