### ISSUE TITLE
Recent update breaks plugin for earlier versions of certbot

### ISSUE THREAD

**Issue by TheLugal** [domeneshop/certbot-dns-domeneshop#8]
The current version of the plugin does not work distros with a slower release cycle, like debian 11, that currently has `certbot 1.12.0` in the repos.

Current workaround is to downgrade the plugin.
```sh
pip3 install --upgrade certbot-dns-domeneshop==0.2.8
```

**Comment by jani** [comment]
Sorry for the late response.

Certbot 2.0.0 introduced backwards incompatible changes, which was why our 0.2.9 was released. 0.2.8 is needed for versions before 2.0.0.

Certbot 2.1.0 introduced a compat-shim that makes our update 0.2.9 temporarily unnecessary, until Certbot removes the compat-shim again.
